sudo: false
language: cpp

compiler:
    - gcc
    - clang

os:
    - linux

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - gcc-6-multilib
        - g++-6
        - g++-6-multilib
        - libvulkan-dev
        - libvulkan1
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
